server:
  shutdonw: graceful
  port: 8080
  servlet:
    encoding:
      charset: utf-8
      enabled: true
      force: true
    context-path: /

logging:
  file:
    name: ${user.dir}/log/test.log
  level:
    org.hibernate: debug
    spring.jpa.show-sql: debug
    spring.jpa.properties.hibernate.format_sql: debug
    com.test.springtest: debug
    com.test.springtest.entity: error

spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    hikari:
      #driver-class-name: org.h2.driver
      jdbc-url: jdbc:h2:mem:test
      username: sa
      password:
      auto-commit: true
      connection-test-query: SELECT 1 FROM DUAL

    jpa:
      open-in-view: true
      hibernate:
        ddl-auto: none
        use-new-id-generator-mappings: false
      show-sql: true
      properties:
        hibernate.format_sql: true

    jackson:
      serialization:
        fail-on-empty-beans: false
