server:
  shutdown: graceful
  port: 8080
  servlet:
    encoding:
      charset: utf-8
      enabled: true
      force: true
    context-path: /

logging:
  file:
    name: ${user.dir}/log/test.log
  level:
    com.test.springtest: debug

spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      auto-commit: true
      connection-test-query: SELECT 1 FROM DUAL
      validation-timeout: 10000
      maximum-pool-size: 5
      connection-timeout: 300000
      pool-name: test-h2-pool

  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
      use-new-id-generator-mappings: false

  jackson:
    serialization:
      fail-on-empty-beans: false

  security:
    oauth2:
      client:
        registration:
          kakao:
            clientId: kakao-client-id
            clientSecret: kakao-client-secret
          naver:
            clientId: naver-client-id
            clientSecret: naver-client-secret